name: PySpark CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pyspark-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyspark

      - name: Run PySpark job
        run: |
          mkdir -p output
          python app.py
          
      - name: Upload Parquet file
        uses: actions/upload-artifact@v3
        with:
          name: customers-parquet
          path: output/customers.parquet


